function DBTables() {
	#region TABLE: CLIENTS
	#macro CLIENTS_SOCKETID 0
	#macro CLIENTS_IP 1
	#macro CLIENTS_COOPID 2
	#macro CLIENTS_COOPPASSWORD 3
	#macro CLIENTS_HOST 4
	#macro CLIENTS_SOCKETID_ON_COOP 5
	#macro CLIENTS_SOCKETID_ON_SERVER 6
	#endregion
}